version: '3.7'
services:

  proxy:
    build:
      context: .
      args:
        link: 'iris'
        port: '52773'
    image: proxyiris:latest
    ports:
    - "443:443"

  iris:
#   image: store/intersystems/iris:2019.1.0.510.0-community
    image: intersystemsdc/irishealth-community
# :2020.4.0.524.0-zpm
    hostname: iris

